### PR TITLE
Reimplement Gravestones in the DarkForest Scene

### LINKED ISSUE #141: Reimplement Gravestones in the DarkForest Scene
### Scope
We need to reimplement the gravestones in the DarkForest scene. They were previously removed due to a bug, but this issue has been resolved in recent commits. It is now time to reintroduce each gravestone.

Please use the attached image to see the original positions of the gravestones in the scene and place them accordingly.
image

### How to implement the issue?
- We already have an example gravestone available. Your task is to duplicate the Grave object, which includes the entire gravestone along with its components.
- Duplicate the Grave object as many times as necessary and position the duplicates around the map so that it resembles the previous design shown in the reference image.

### How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

### PR DESCRIPTION
**Pull request by 0xDeon**
### Closes #141 
- Duplicated gravestone game object
- Repositioned all duplicates accordingly
- Fixed scene issue

## Summary by CodeRabbit

- **Chores**
	- Updated the default solution file for .NET tooling in Visual Studio Code.

### CODE REVIEW

**Comment by 0xDeon** [comment]
@joeperpetua @jsandinoDev Please review

**Comment by jimenezz22** [comment]
> @joeperpetua @jsandinoDev Please review

they are not maintainers

**Comment by 0xDeon** [comment]
@jimenezz22 Please review

**Review by jimenezz22 — APPROVED** [review]
pr already tested on my local repo and works successfully

**Pull request merged**
