### PR TITLE
Set new map for the forest

### PR DESCRIPTION
**Pull request by RolandoDrRobot**
Captura de pantalla 2024-09-22 a la(s) 3 52 56 p  m
Captura de pantalla 2024-09-22 a la(s) 3 51 33 p  m
Captura de pantalla 2024-09-22 a la(s) 3 51 41 p  m
Captura de pantalla 2024-09-22 a la(s) 3 51 52 p  m
Captura de pantalla 2024-09-22 a la(s) 3 52 20 p  m
Captura de pantalla 2024-09-22 a la(s) 3 52 31 p  m
Captura de pantalla 2024-09-22 a la(s) 3 52 41 p  m
Captura de pantalla 2024-09-22 a la(s) 3 53 53 p  m

## Summary by CodeRabbit

- **New Features**
	- Introduced multiple new MonoBehaviour assets, including `RA_Jungle_11`, `RA_Jungle_12`, `RA_Jungle_13`, `RA_Jungle_16`, `RA_Jungle_17`, `RA_Jungle_18`, `RA_Jungle_19`, `RA_Jungle_2`, `RA_Jungle_20`, `RA_Jungle_21`, `RA_Jungle_3`, `RA_Jungle_4`, `RA_Jungle_5`, `Stage 3 - Packed GBc_5`, `Stage 4 - Packed GBccccc_11`, `Stage 4 - Packed GBccccc_12`, `Stage 4 - Packed GBccccc_2`, `Stage 4 - Packed GBccccc_22`, `Stage 5 - Packed Base_12`, `Stage 5 - Packed Base_20`, `Stage 5 - Packed Base_42`, `Stage 5 - Packed Base_5`, `Stage 5 - Packed Base_52`, `Stage 5 - Packed Based_32`, `Stage 5 - Packed Based_34`, `Stage 5 - Packed Based_41`.
	- Added new tile entries and updated existing tile properties in `AllTrees.prefab` and `forest.prefab`.

- **Bug Fixes**
	- Removed unused import in `NPCInteraction.cs` to streamline the code.

- **Documentation**
	- Updated metadata files to reflect new assets and configurations.

### CODE REVIEW

**Review by juandiegocv27 — COMMENTED** [review]
Love the new implementations, but you put everything like a solid object
image
image


so i cannot move from here, like i dont see the logic of the player can´t move in the flowers.

**Review by juandiegocv27 — CHANGES_REQUESTED** [review]
image

Theres too many Beasts in the screen, love the idea of the baby beasts in the forest, but the last tranformation around there I think its too much visually for the public, maybe try to remove the beats and just left the baby ones

**Comment by juandiegocv27** [comment]
image

Love the creation of this zone, but for the spawnpoint its too tight, fix those things please

**Review by jimenezz22 — COMMENTED** [review]
Love the new map. 

Here some comments:

- fix trees colliders
- fix sorting layers between trees and fountain
- remove npc's
- add movement or breathing animations to the beasts in the daycare 
- The paths look very geometric, add borders
- remove the giant beasts on the map
- the entrance to the cave must be a cave, not a house
- add colliders to the beasts
- delimit the map so that it does not give the player the impression that the map extends

**Pull request merged**
