### PR TITLE
New character design: Crystal theme babybeast

### LINKED ISSUE #138: New BabyBeast Asset and Animations – Crystal Theme💎
### Scope  
We need to create a new BabyBeast asset with a **Crystal Theme🧊** for OD Hack 10. The design must maintain consistency with the current app's BabyBeast style, specifically the Baby Rabbit, while introducing unique crystalline elements. The goal is to enhance the app's variety and visual appeal with this themed asset.

### How BabyBeasts are currently designed?  
- BabyBeasts are designed as cute animals with a consistent style: rounded proportions, pastel tones, and clean, minimal details.  
- The Baby Rabbit model is the reference. It is stylized with simple shapes and subtle animations that make it feel alive in the app.

babybeast copyresize

---

### Requirements  
1. **Design the Crystal BabyBeast💎:**  
   - Use the Baby Rabbit as a base for style and proportions.  
   - Add crystal-like features such as translucent or glowing body parts.  
   - Ensure the design feels cohesive with the current BabyBeasts.

2. **Create Animations:**  
   - Add animations that emphasize the crystalline elements:  
     - Subtle shimmering effects.  
     - Pulsating glows on crystal accents. 💠 

3. **Maintain Consistency:**  
   - Match the style of the current BabyBeasts, including similar proportions, color palettes, and aesthetic logic.  

---

### How to implement?  
1. Download and use any pixel art toolkit.
2. Create and Animate the new Beast.
3. Save it to Assets/BabySprites in this repo, please give us the asset with their respective Sprites.
4. Let us know with pr and talking directly to me https://t.me/juandixcode or in the community group: https://t.me/+aqxlW9ACIt5jODEx

---

### Cool Tools to Use  
- For creating and animating pixel art, we recommend using **[Aseprite](https://www.aseprite.org/)**. It’s a powerful tool for creating sprites, animations, and other pixel art elements or use another Toolkit of your choice.

### How to apply?  
Follow the contribution guidelines in the [README](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file.  

Let me know by tagging me or @jimenezz22 😇🫶🏻

### PR DESCRIPTION
**Pull request by sandragcarrillo**
Adding the design for a new Crystal Theme character: a crystal penguin

# Pull Request Overview

## 📝 Summary
1. Design the Crystal BabyBeast: Created a design for a crystal baby penguin 
2. Add animations that emphasize the crystalline elements (Subtle shimmering effects. Pulsating glows on crystal accents)

### Related Issues
- Closes #138 

### Type of Change
Mark with an `x` all the checkboxes that apply (like `[x]`).
- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

### What's Changed

Created design for the Crystal Theme BabyBeast, a penguin. Created the animations to show crystalline elements of the character. 

### Implementation Details
Used Aseprite as the tool to create the pixel art (design an animations). 

## 🔜 Next Steps
Submit the animations

### CODE REVIEW

**Comment by juandiegocv27** [comment]
love it @sandragcarrillo, add the animations please and let me know

**Comment by sandragcarrillo** [comment]
Hi @juandiegocv27, I added one animation and sprite for it. Can you review it and let me know your feedback please 🙏

**Comment by juandiegocv27** [comment]
> Hi @juandiegocv27, I added one animation and sprite for it. Can you review it and let me know your feedback please 🙏

love it, continue with the last animations and its ready to go

**Comment by sandragcarrillo** [comment]
Hi @juandiegocv27, animations are done! 

Let me know if you have any improvements to make, I added the same food that the rabbit is eating because i wasn’t sure if I could create a new food for the penguin (like a small fish or something). 

It's been amazing to contribute to ByteBeast, hope to continue doing so!

**Comment by juandiegocv27** [comment]
LGTM!

**Comment by juandiegocv27** [comment]
> Hi @juandiegocv27, animations are done!
> 
> Let me know if you have any improvements to make, I added the same food that the rabbit is eating because i wasn’t sure if I could create a new food for the penguin (like a small fish or something).
> 
> It's been amazing to contribute to ByteBeast, hope to continue doing so!

its perfect, hope to see you in new contributions, LGTM!

**Pull request merged**
