### PR TITLE
docs: add documentation to c# scripts

### LINKED ISSUE #96: Document Code in C# Scripts
### Scope
We need to document all the code in the files inside Assets/Scripts path

### To do:
- Understand the all the code/classes/methods/functions in the files and their conecctions with other classes in other scripts
- Document these files in a format similar to JavaDoc for example, but for C# scripts.
- Explain what each class, each method, each function, each flow control, etc. does. We need to have all these scripts fully documented.
### How to apply?
Please follow the contribution guidelines in the [readme](https://github.com/ByteBuildersLabs/ByteBeastsFrontend/blob/main/README.md) file

### PR DESCRIPTION
**Pull request by NueloSE**
Fixes #96

## Summary by CodeRabbit

- **Documentation Enhancements**
	- Extensive XML documentation comments added across multiple classes to improve clarity and maintainability.
	- Key classes documented include `AreaEntrance`, `AreaExit`, `AttackEffect`, `AudioManager`, `BattleManager`, `DialogManager`, `Shop`, and many others.
	- Methods and properties now include detailed summaries explaining their roles and functionalities.

- **New Features**
	- Introduction of new public methods and fields in various classes, such as `SetBounds` and `ActivateJoystick` in `PlayerController`.

- **Improvements**
	- Enhanced documentation for existing methods to clarify their functionality without altering core logic.

### CODE REVIEW

**Comment by NueloSE** [comment]
@jimenezz22, the draft is still in progress and not yet ready for review. I plan to submit a final PR today, which will include documentation for the remaining scripts. Following my personal review, I’ll ensure it’s ready for team review by the end of the day. I believe the draft aligns with the task requirements, and I’ll continue in this direction unless advised otherwise.

**Comment by jimenezz22** [comment]
> @jimenezz22, the draft is still in progress and not yet ready for review. I plan to submit a final PR today, which will include documentation for the remaining scripts. Following my personal review, I’ll ensure it’s ready for team review by the end of the day. I believe the draft aligns with the task requirements, and I’ll continue in this direction unless advised otherwise.

Understood sir, please requests my review when pr is ready

**Comment by NueloSE** [comment]
@jimenezz22 This PR is ready for your review. I would appreciate any feedback you may have.

**Comment by jimenezz22** [comment]
> @jimenezz22 This PR is ready for your review. I would appreciate any feedback you may have.

thanks, i will review it in few hours

**Review by jimenezz22 — APPROVED** [review]

**Comment by jimenezz22** [comment]
thanks for your contribution @NueloSE

**Pull request merged**
