### PR TITLE
Feat: Change gameplay panel assets

### LINKED ISSUE #97: Change Assets of Gameplay Panels
### Scope
- We need to change the background assets of the current panels in the game. Specifically, we need to change the panel where the beasts are displayed and the panel showing the rewards obtained when a battle ends.

- This panel is currently black, and we need to replace it with another asset we already have. This asset will be provided to the contributor once the issue is assigned.

### How this panel is implemented
- This panel is implemented on the prefab called "UI Canvas", this prefab is located in the following path: Assets/Prefabs/UI Canvas.prefab 

- This is how panel hierarchy looks in Unity
Screenshot 2024-10-23 at 1 31 55 PM

- This is how the panel looks during gameplay; it is activated by touching the screen with two fingers.

Screenshot 2024-10-23 at 1 29 02 PM

- This is how panel rewards looks when a battle ends
Screenshot 2024-10-23 at 1 38 35 PM

### PR DESCRIPTION
**Pull request by joeperpetua**
Closes: #97 

- Added new panel assets in three different sizes (S, M, L) to `Assets/Battle Assets/Art/UI/`
- Applied new assets to following objects:
  - `UI Canvas/Menu/Buttons/Stats Button`
  - `UI Canvas/Menu/Buttons/Close Button`
  - `UI Canvas/Menu/Char Infos/Char info {1..3}`
  - `UI Canvas/Menu/Status Window`
  - `UI Canvas/Menu/Status Window/Buttons/P{1..3} Button`
  - `UI Canvas/Battle Reward`
  - `UI Canvas/Battle Reward/Close Button`

If there is any change needed, let me know :)

Screenshots of end result:

image

image

image

## Summary by CodeRabbit

- **New Features**
	- Introduced new metadata files for texture assets, enhancing texture import configurations.
	- Updated UI elements in the BattleManager prefab, including sprite modifications and layout adjustments for improved user experience.

- **Bug Fixes**
	- Improved functionality of spell buttons, ensuring correct costs and effects are displayed.

- **Chores**
	- Updated sprite references across multiple UI components for consistency.

### CODE REVIEW

**Comment by jimenezz22** [comment]
I will review this changes in my local repo to tests everything works as expected

**Review by jimenezz22 — APPROVED** [review]
pr already tested on my local repo and successfully works, I will merge it in the next hours. Thank you for your work @joeperpetua

**Comment by joeperpetua** [comment]
@jimenezz22 nice, thanks for the chance to contribute! 
Sorry for the delay, got a tough issue with Starknet.Quest that had me busy all weekend 😅😂

**Comment by jimenezz22** [comment]
> @jimenezz22 nice, thanks for the chance to contribute! Sorry for the delay, got a tough issue with Starknet.Quest that had me busy all weekend 😅😂

hahaha no problem sir, we understand that. We are going to open more issues for contributors if you want to continue contributing to our project, stay tuned

**Comment by joeperpetua** [comment]
> > @jimenezz22 nice, thanks for the chance to contribute! Sorry for the delay, got a tough issue with Starknet.Quest that had me busy all weekend 😅😂
> 
> hahaha no problem sir, we understand that. We are going to open more issues for contributors if you want to continue contributing to our project, stay tuned

sure thing, it will be a pleasure 😎😎

**Comment by jimenezz22** [comment]
> > > @jimenezz22 nice, thanks for the chance to contribute! Sorry for the delay, got a tough issue with Starknet.Quest that had me busy all weekend 😅😂
> > 
> > 
> > hahaha no problem sir, we understand that. We are going to open more issues for contributors if you want to continue contributing to our project, stay tuned
> 
> sure thing, it will be a pleasure 😎😎

what's your telegram homie?

**Comment by joeperpetua** [comment]
> > > > @jimenezz22 nice, thanks for the chance to contribute! Sorry for the delay, got a tough issue with Starknet.Quest that had me busy all weekend 😅😂
> > > 
> > > 
> > > hahaha no problem sir, we understand that. We are going to open more issues for contributors if you want to continue contributing to our project, stay tuned
> > 
> > sure thing, it will be a pleasure 😎😎
> 
> what's your telegram homie?

@godpers ✌️

**Review by jimenezz22 — APPROVED** [review]
pr already tested on my local repo and successfully works

**Pull request merged**
