### PR TITLE
babybeast dark theme wolf pup

### LINKED ISSUE #162: New BabyBeast Asset and Animations – Darkness Theme🌑 (Wolf Pup)
## Scope
We need to create a new BabyBeast asset with a **Darkness Theme🌑** for a Wolf Pup. The design must maintain consistency, while introducing unique dark and shadowy features. 
---

## What is a BabyBeast?
BabyBeasts are designed as cute magical animals with a consistent style: rounded proportions, soft tones, and minimal yet expressive details.  
You can use this one as an example of a Dark Theme Assets/BabySprites/babybeast-dark-magic-theme-base.gif

---

### Design the Darkness BabyBeast🌑:
- Use the Baby **Assets/BabySprites/babybeast-dark-magic-theme-base.gif** as a base for style and proportions.  
- Add shadowy and dark features, such as:  
  - Deep purple or black tones with subtle gradients. 🟣⚫  
  - Smoky or mist-like accents around the body. 🌫️  
  - Glowing eyes with a mysterious hue. 👀✨  

### Create Animations:
1. **Idle Animation (breathing)**:  
   - Subtle shadowy pulsations or mist swirling around the wolf pup.  
2. **Additional Animations**:  
   - Eating animation: Playful chewing of a bone but calculated with bright eyes.
   - Sleeping animation: Curling into a ball as shadows envelop it.  
   - Happiness animation: Energetic tail wagging with a shadowy ripple effect.  
   - Bathing animation: Mist-like ripples flowing across its fur.  

### Maintain Consistency:
- Match the proportions, color palettes, and aesthetic logic of the current BabyBeasts.  
- All animations should feel smooth and aligned with the game’s magical and shadowy theme.

---

## How to Implement?
1. Use any pixel art or sprite animation toolkit of your choice.
2. Create and animate the **Darkness BabyBeast** (Wolf Pup).
3. Save all assets to the `Assets/BabySprites` folder in this repository, ensuring proper naming conventions for the files.

---

## Cool Tools to Use
- **Aseprite**: A powerful tool for creating and animating sprites and pixel art.  
- **Piskel**: A free online tool for sprite creation and animation.  
- Feel free to use any toolkit that works best for you.

---

## How to Apply?
1. Follow the contribution guidelines provided in the README file.  
2. Submit your pull request with the asset and animations in their respective folders.  
3. Ensure all animations are properly tested before submission.

---

We’re excited to see your contribution! 🐺🌑

### PR DESCRIPTION
**Pull request by Tonyverse-ops**
# Pull Request Overview

## 📝 Summary
Creates a new BabyBeast.

### Related Issues
- Closes #162

### Type of Change
Mark with an `x` all the checkboxes that apply (like `[x]`).
- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

### What's Changed
New BabyBeast Asset and Animations – Darkness Theme🌑 (Wolf Pup)

### CODE REVIEW

**Review by jimenezz22 — CHANGES_REQUESTED** [review]
Could you please give him a wolf appearance? This asset looks very similar to the fox we already have. Maybe you could use this as a guide: https://www.shutterstock.com/image-vector/cute-cartoon-wolf-isolated-on-white-2485883225

Remember to do the other animations: eating, jumping, sleeping, bathing

**Comment by jimenezz22** [comment]
@Tonyverse-ops is this pr ready for review?

**Comment by Tonyverse-ops** [comment]
@jimenezz22 yes, the pr is ready for review let me know if you have any further changes or corrections .

**Review by jimenezz22 — CHANGES_REQUESTED** [review]
Just rename the files to follow this format: BabyWolf-Dark-Eat.gif

**Review by jimenezz22 — APPROVED** [review]

**Pull request merged**
