### PR TITLE
feat: Add home button

### LINKED ISSUE #98: Add Menu Button
### Scope
- We need to add a new buttom in the game scenes that allows the acces to the gamplay panels, take a look in the issue #97 to undestand more about what is this panels. 
 - The buttom should be implemented in the path: Assets/Prefabs/UI Canvas.prefab in the component: Meu/Buttoms
 - The asset for the buttom will be provided to the contributor once the issue is assigned.
 - Please put this assets in the path Assets/Battle Assets/Art/UI
 ### This is how panel hierarchy looks in Unity
Screenshot 2024-10-23 at 2 03 37 PM

### PR DESCRIPTION
**Pull request by jsandinoDev**
Closes: #98 

- Added HomeButton & PanelAssets to ```Assets/Battle Assets/Art/UI```
- Added Home Button with the new assets
- Added **Open menu** functionality to the Home Button
- Remove the **Right Click** Open Menu functionality

First time working in Unity so any changes or improvements just let me know.

Screenshot of the result:

telegram-cloud-photo-size-1-4972048287712521801-y

## Summary by CodeRabbit

- **New Features**
	- Introduced new metadata files for various UI and texture assets, enhancing asset management and organization.
	- Added a "Home Button" and "Home Button Panel" to the UI Canvas prefab, improving user interaction.
	- Implemented a new method `OpenMenu()` in the GameMenu class for streamlined menu activation.

- **Bug Fixes**
	- Removed the outdated `Update()` method in GameMenu, simplifying menu interactions.

- **Chores**
	- Created several metadata files for texture assets, ensuring proper configuration for rendering and performance.

### CODE REVIEW

**Review by jimenezz22 — CHANGES_REQUESTED** [review]
@jsandinoDev the button looks with diferent dimensions when I ran your branch in my local repo. Could you fix it please?

Screenshot 2024-10-29 at 1 06 44 PM
Screenshot 2024-10-29 at 1 06 50 PM
Screenshot 2024-10-29 at 1 07 13 PM

**Comment by jsandinoDev** [comment]
@jimenezz22 Fixed.

I add the m_PreserveAspect to the **Home Button Panel** and adjust the rect transformation.

Here are the different fixed displays:


Free Aspect
Screenshot 2024-10-29 at 2 24 51 PM


16:9 Aspect

Screenshot 2024-10-29 at 2 25 11 PM

16:10 Aspect

Screenshot 2024-10-29 at 2 25 35 PM

**Comment by jsandinoDev** [comment]
Hi @jimenezz22 I just merge the missing changes of the main branch with this PR branch. Please review!

**Review by jimenezz22 — APPROVED** [review]
pr already tested on my local repo and successfully works

**Pull request merged**
