### PR TITLE
baby eagle animations

### LINKED ISSUE #165: New BabyBeast Asset and Animations – Crystal Theme💎 (Eagle)
## Scope
We need to create a new BabyBeast asset with a **Crystal Theme💎** for a Baby Eagle. The design must maintain consistency, while introducing unique translucent and light-refracting features.

---

## What is a BabyBeast?
BabyBeasts are designed as cute magical animals with a consistent style: rounded proportions, soft tones, and minimal yet expressive details.  
You can use this one as an example of a Crystal Theme: `Assets/BabySprites/crystalbabybeast.gif`

---

### Design the Crystal BabyBeast💎:
- Use the `Assets/BabySprites/crystalbabybeast.gif` as a base for style and proportions.  
- Add crystal-like features, such as:  
  - Translucent feathers that refract light into rainbow colors. 🌈🦅  
  - A glowing body with subtle shimmering effects. ✨💫  
  - Elegant and sharp details on the wings and beak.  

### Create Animations:
1. **Idle Animation (breathing)**:  
   - Gentle wing movements with light refracting through the feathers.  
2. **Additional Animations**:  
   - Eating animation: Precise pecking at food while light shimmers on its feathers.  
   - Sleeping animation: Wings folding gracefully with light dimming softly.  
   - Happiness animation: Energetic flapping with rainbow-like sparkles.  
   - Bathing animation: Light ripples shimmering across its translucent feathers.  

### Maintain Consistency:
- Match the proportions, color palettes, and aesthetic logic of the current BabyBeasts.  
- All animations should feel smooth and aligned with the game’s magical and crystalline theme.

---

## How to Implement?
1. Use any pixel art or sprite animation toolkit of your choice.  
2. Create and animate the **Crystal BabyBeast** (Eagle).  
3. Save all assets to the `Assets/BabySprites` folder in this repository, ensuring proper naming conventions for the files.

---

## Cool Tools to Use
- **Aseprite**: A powerful tool for creating and animating sprites and pixel art.  
- **Piskel**: A free online tool for sprite creation and animation.  
- Feel free to use any toolkit that works best for you.

---

## How to Apply?
1. Follow the contribution guidelines provided in the README file.  
2. Submit your pull request with the asset and animations in their respective folders.  
3. Ensure all animations are properly tested before submission.

---

We’re excited to see your contribution! 🦅💎

### PR DESCRIPTION
**Pull request by suhas-sensei**
# Pull Request Overview

## 📝 Summary
Introduces animations of Baby Eagle.

### Related Issues
- Closes #165 

### Type of Change
Mark with an `x` all the checkboxes that apply (like `[x]`).
- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by juandiegocv27 — CHANGES_REQUESTED** [review]
please change the visual design of the eagle please, do it similar to this isssues #171 #170

**Comment by juandiegocv27** [comment]
@suhas-sensei let you some review, please do the required changes

**Comment by suhas-sensei** [comment]
Sure ok, I'll revise the designs, thanks for the review

**Comment by jimenezz22** [comment]
@suhas-sensei any updates?

**Comment by suhas-sensei** [comment]
yes ser, sending the assets today

**Pull request closed without merging**
